package azw3

import (
	"bytes"
	"fmt"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"math/rand"
	"os"
	"sort"
	"time"

	"github.com/leotaku/mobi"
	"github.com/leotaku/mobi/records"
	"golang.org/x/text/language"
)

// Id identifies a resource (chapter, image, or stylesheet) previously
// added to a Book. It has no meaning outside the Book that returned it,
// except for image ids: those double as a ready-to-use XHTML src
// attribute value (see AddImage).
type Id string

// Book is the entry point for building an AZW3 ebook. Construct one with
// New, configure it with the setters and Add* methods below, then call
// Write or Serialize.
//
// The zero value is not usable; construct a Book with New. A Book is not
// safe for concurrent use.
type Book struct {
	title        string
	authors      []string
	contributors []contributor
	publishers   []string
	language     language.Tag
	description  string
	published    time.Time
	uniqueID     uint32

	fixedLayout bool
	rightToLeft bool

	chapters []*chapterEntry
	css      []string

	images     []image.Image
	imagesByID map[Id]image.Image
	coverImage image.Image

	usedPaths map[string]bool
	seq       int

	nav []*Navpoint
}

type contributor struct {
	name string
	role string
}

type chapterEntry struct {
	id      Id
	title   string
	content string
	order   int
	seq     int
}

// New creates a new, empty Book with an automatically generated
// UniqueID (see SetUniqueID). It has no title, content, or navigation
// until you add them.
func New() *Book {
	return &Book{
		uniqueID:   rand.Uint32(),
		imagesByID: make(map[Id]image.Image),
		usedPaths:  make(map[string]bool),
	}
}

// --- Metadata ---

// SetTitle sets the book's title, replacing any title set previously.
func (b *Book) SetTitle(title string) {
	b.title = title
}

// AddAuthor appends an author to the book's author list.
func (b *Book) AddAuthor(author string) {
	b.authors = append(b.authors, author)
}

// AddContributor appends a contributor with the given MARC relator role
// code (e.g. "edt" for editor, "ill" for illustrator). Returns
// ErrInvalidContributorRole for an unrecognized code.
func (b *Book) AddContributor(name, role string) error {
	if !marcRelatorCodes[role] {
		return ErrInvalidContributorRole
	}
	b.contributors = append(b.contributors, contributor{name: name, role: role})
	return nil
}

// AddPublisher appends a publisher to the book's publisher list.
func (b *Book) AddPublisher(publisher string) {
	b.publishers = append(b.publishers, publisher)
}

// AddLanguage sets the book's language. l must be a valid BCP 47 tag
// (e.g. "en", "de-DE"); otherwise ErrInvalidLanguage is returned.
func (b *Book) AddLanguage(l string) error {
	tag, err := language.Parse(l)
	if err != nil {
		return ErrInvalidLanguage
	}
	b.language = tag
	return nil
}

// AddDescription sets the book's description/summary metadata field.
func (b *Book) AddDescription(desc string) {
	b.description = desc
}

// SetUniqueID sets the book's unique numeric identifier, replacing the
// one randomly generated by New. It seeds the fake ASIN Kindle uses to
// associate a sideloaded cover/thumbnail with this book.
func (b *Book) SetUniqueID(id uint32) {
	b.uniqueID = id
}

// UniqueID returns the book's current unique numeric identifier.
func (b *Book) UniqueID() uint32 {
	return b.uniqueID
}

// SetPublishedDate sets the book's publication date.
func (b *Book) SetPublishedDate(t time.Time) {
	b.published = t
}

// SetFixedLayout marks the book as fixed-layout (e.g. for comics/
// picture books) rather than reflowable.
func (b *Book) SetFixedLayout(v bool) {
	b.fixedLayout = v
}

// SetRightToLeft sets the book's primary reading direction.
func (b *Book) SetRightToLeft(v bool) {
	b.rightToLeft = v
}

// --- Content ---

// AddChapter appends contents (XHTML) to the book's flat reading-order
// flow. path is a caller-chosen, book-internal name for this chapter
// (used to detect duplicates; it is not a filesystem path). order
// controls its position in the flow; ties are broken by insertion order,
// and omitting order defaults to 0. title is used for the chapter's
// entry in the Kindle reader's native, flat "Go To" chapter list, and
// also as the label available to Book.AddNavpoint.
//
// Returns ErrDuplicatePath if path is already in use.
func (b *Book) AddChapter(path, title, contents string, order ...int) (Id, error) {
	if b.usedPaths[path] {
		return "", ErrDuplicatePath
	}
	b.usedPaths[path] = true

	o := 0
	if len(order) > 0 {
		o = order[0]
	}

	id := Id(path)
	b.chapters = append(b.chapters, &chapterEntry{
		id:      id,
		title:   title,
		content: contents,
		order:   o,
		seq:     b.nextSeq(),
	})
	return id, nil
}

// AddImage registers image data under path, sniffing its format (JPEG,
// PNG, or GIF) from contents. Unlike EPUB, KF8 has no filesystem-like
// resource paths: path is a caller-chosen, book-internal name used only
// to detect duplicates. The returned Id is directly usable as an XHTML
// src attribute value, e.g.:
//
//	id, _ := b.AddImage("cover-illustration", data)
//	xhtml := fmt.Sprintf(`<img src="%s" alt="..."/>`, id)
//
// Returns ErrUnsupportedImageFormat for any other format, or
// ErrDuplicatePath if path is already in use.
func (b *Book) AddImage(path string, contents []byte) (Id, error) {
	if b.usedPaths[path] {
		return "", ErrDuplicatePath
	}

	img, format, err := image.Decode(bytes.NewReader(contents))
	if err != nil {
		return "", ErrUnsupportedImageFormat
	}
	mime, ok := imageMimeTypes[format]
	if !ok {
		return "", ErrUnsupportedImageFormat
	}

	b.usedPaths[path] = true
	b.images = append(b.images, img)
	index := len(b.images) // 1-based position, stable: cover/thumb are appended separately at Realize time
	id := Id(fmt.Sprintf("kindle:embed:%s?mime=%s", records.To32(index), mime))
	b.imagesByID[id] = img
	return id, nil
}

// AddImageFile reads the file at source from disk and registers it under
// path via AddImage.
func (b *Book) AddImageFile(source, path string) (Id, error) {
	contents, err := os.ReadFile(source)
	if err != nil {
		return "", err
	}
	return b.AddImage(path, contents)
}

var imageMimeTypes = map[string]string{
	"jpeg": "image/jpeg",
	"png":  "image/png",
	"gif":  "image/gif",
}

// AddStylesheet registers a CSS stylesheet under path. Unlike EPUB, it
// does not need to be linked manually from chapter XHTML: it is
// automatically applied to every chapter. The returned Id is purely
// informational. Returns ErrDuplicatePath if path is already in use.
func (b *Book) AddStylesheet(path, contents string) (Id, error) {
	if b.usedPaths[path] {
		return "", ErrDuplicatePath
	}
	b.usedPaths[path] = true

	b.css = append(b.css, contents)
	index := len(b.css)
	id := Id(fmt.Sprintf("kindle:flow:%s?mime=text/css", records.To32(index)))
	return id, nil
}

// AddStylesheetFile reads the file at source from disk and registers it
// under path via AddStylesheet.
func (b *Book) AddStylesheetFile(source, path string) (Id, error) {
	contents, err := os.ReadFile(source)
	if err != nil {
		return "", err
	}
	return b.AddStylesheet(path, string(contents))
}

// --- Navigation ---

// AddNavpoint adds a top-level navigation point to the book's table of
// contents tree. See Navpoint.AddNavpoint for nesting, and the package
// doc for how this relates to the flat content flow built by AddChapter.
func (b *Book) AddNavpoint(label, target string, order int) *Navpoint {
	n := &Navpoint{label: label, target: target, order: order}
	b.nav = append(b.nav, n)
	return n
}

// --- Cover ---

// SetCoverImage sets the book's cover to a previously added image,
// identified by the Id returned from AddImage/AddImageFile. Unknown ids
// are ignored.
func (b *Book) SetCoverImage(id Id) {
	if img, ok := b.imagesByID[id]; ok {
		b.coverImage = img
	}
}

// --- Output ---

// Write renders the book and writes it to the file at name. It returns
// ErrNoContent if no chapters have been added.
func (b *Book) Write(name string) error {
	data, err := b.Serialize()
	if err != nil {
		return err
	}
	return os.WriteFile(name, data, 0o644)
}

// Serialize renders the book and returns it as a byte slice. It returns
// ErrNoContent if no chapters have been added.
func (b *Book) Serialize() ([]byte, error) {
	if len(b.chapters) == 0 {
		return nil, ErrNoContent
	}

	mb := b.toMobiBook()
	buf := new(bytes.Buffer)
	if err := realize(mb, buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (b *Book) toMobiBook() mobi.Book {
	entries := make([]*chapterEntry, len(b.chapters))
	copy(entries, b.chapters)
	sort.SliceStable(entries, func(i, j int) bool {
		return entries[i].order < entries[j].order
	})

	chapters := make([]mobi.Chapter, len(entries))
	for i, e := range entries {
		chapters[i] = mobi.Chapter{
			Title:  e.title,
			Chunks: mobi.Chunks(e.content),
		}
	}

	authors := make([]string, len(b.authors))
	copy(authors, b.authors)

	contributors := make([]string, len(b.contributors))
	for i, c := range b.contributors {
		contributors[i] = c.name
	}

	publisher := ""
	if len(b.publishers) > 0 {
		publisher = b.publishers[0]
	}

	return mobi.Book{
		Title:         b.title,
		Authors:       authors,
		Contributors:  contributors,
		Publisher:     publisher,
		CreatedDate:   time.Now(),
		PublishedDate: b.published,
		Language:      b.language,
		FixedLayout:   b.fixedLayout,
		RightToLeft:   b.rightToLeft,
		Chapters:      chapters,
		CSSFlows:      b.css,
		Images:        b.images,
		CoverImage:    b.coverImage,
		UniqueID:      b.uniqueID,
	}
}

func (b *Book) nextSeq() int {
	b.seq++
	return b.seq
}

// realize converts mb to a PalmDB database and writes it to w, recovering
// from panics documented by leotaku/mobi (template expansion errors) and
// reporting them as a plain error instead, per this package's no-panic
// contract. A book with no chapters is guarded against before this is
// called, which is the other documented panic source.
func realize(mb mobi.Book, w *bytes.Buffer) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("azw3: failed to render book: %v", r)
		}
	}()
	db := mb.Realize()
	return db.Write(w)
}
