// Package azw3 provides a write-only, high-level API for building AZW3
// (Kindle KF8) ebooks. It wraps github.com/leotaku/mobi, which implements
// the underlying KF8 record and container format.
//
// Its shape mirrors github.com/writingtoole/epub: a Book you configure
// with plain Add/Set verb methods, no fluent chaining, no functional
// options, errors returned rather than panics.
//
// # Scope
//
// azw3 is write-only: it has no facilities for reading or modifying
// existing AZW3/MOBI files.
//
// # Content vs. navigation
//
// As in EPUB, content and navigation are separate concerns. AddChapter
// appends XHTML to the book's flat reading-order flow (the KF8 format,
// like EPUB's spine, has no native concept of nested content). Book.Nav
// returns the root of a Navpoint tree that can be nested arbitrarily
// deep; each Navpoint points at an anchor id present somewhere in the
// content flow. This mirrors the way EPUB separates its flat spine from
// its hierarchical nav/NCX document, and is how azw3 offers a nested
// table of contents despite the underlying flat content model.
//
// Note that the Kindle reader's own native "Go To" chapter list is
// generated by leotaku/mobi directly from the flat chapter flow, and
// will not reflect Navpoint nesting; azw3's Navpoint tree drives its own
// generated in-book table of contents page and the KF8 NCX/landmarks
// data, not that native list.
package azw3
